version: '3'
services:
  backend:
      build: .
      container_name: flask_application
      ports:
        - "9000:5000"  
      volumes:
          - new-vol:/app
      environment:
           FLASK_DEBUG: "true"
  redis:
     image: "redis:alpine"

volumes:
    new-vol: {}
